base/urls.py
from django.urls import path

from .views import AboutUsView, ContactView, TermAndConditionView

urlpatterns = [
    path('contact/', ContactView.as_view(), name='contact'),
    path('ternsandconditions/', TermAndConditionView.as_view(), name='terms_and_conditions'),
    path('aboutus/', AboutUsView.as_view(), name='aboutus'),

]

dashboard/urls.py
from django.urls import path

from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardView.as_view(), name='home'),
    # user 
    path('user/', UserListView.as_view(), name='user_list'),
    path('user/approved/', ApprovedUserList.as_view(), name='approved_users'),
    path('user/unapproved/', UnapprovedUserList.as_view(), name='unapproved_users'),
    path('user/<str:username>/', UserDetail.as_view(), name='user_detail'),

    path('user/<str:username>/accept/', ApproveUser.as_view(), name='approve'),
    path('user/<str:username>/reject/', RejectUser.as_view(), name='reject'),
    path('user/<str:username>/book/receive/', ReceiveBook.as_view(), name='receive_book'),

    # books
    path('book/add/', AddBook.as_view(), name='add_book'),
    path('book/', BookList.as_view(), name='book_list'),
    path('book/available/', AvailabelBookList.as_view(), name='available_books'),
    path('book/unavailable/', UnavailabelBookList.as_view(), name='unavailable_books'),

    path('book/<str:slug>/', BookDetail.as_view(), name='book_details'),
    path('book/<str:slug>/update/', UpdateBook.as_view(), name='book_update'),
    path('book/delete', DeleteBook.as_view(), name='book_delete'),

    # deposit
    path('deposit/', DepositList.as_view(), name='deposit_list'),
    path('deposit/<int:pk>/', DepositDetail.as_view(), name='deposit_detail'),
    path('deposit/<int:pk>/verify/', VerifyDeposit.as_view(), name='verify'),
    path('deposit/<int:pk>/unverify/', RejectDeposit.as_view(), name='unverify'),

    # category
    path('category/add/', AddCategory.as_view(), name='add_category'),
    path('category/', CategoryList.as_view(), name='category_list'),
    path('category/<slug:slug>/', CategoryDetail.as_view(), name='category_detail'),
    path('category/<slug:slug>/update/', CategoryUpdate.as_view(), name='category_update'),
    path('category/delete', CategoryDelete.as_view(), name='category_delete'),

    # RequestList
    path('request/', RequestList.as_view(), name='request_list'),

    # orders
    path('orders/', OrderList.as_view(), name='orders'),
    path('orders/delivered/', CompletedOrderList.as_view(), name='delivered_orders'),
    path('orders/canceled/', CanceledOrderList.as_view(), name='canceled_orders'),
    path('orders/dispatched/', DispatchedOrderList.as_view(), name='dispatched_orders'),

    path('orders/<int:pk>/dispatch/', DispatchOrder.as_view(), name='dispatched'),
    path('orders/<int:pk>/cancel/', CanceleOrder.as_view(), name='canceled'),
    path('orders/<int:pk>/delivered/', DelivereOrder.as_view(), name='delivered'),

    # search
    path('user/search', UserSearch.as_view(), name='user_search'),
    path('book/search', BookSearch.as_view(), name='book_search'),
    path('order/search', OrderSearch.as_view(), name='order_search'),

    # ads
    path('ads/', AdsView.as_view(), name='ads'),
    path('ads/<int:pk>/', AdsDetailView.as_view(), name='ad_details'),
    path('ads/add/', CreateAd.as_view(), name='ad_create'),
    path('ads/<int:pk>/update/', UpdateAd.as_view(), name='ad_update'),
    path('ads/<int:pk>/delete', DeleteAd.as_view(), name='ad_delete'),

    # contact
    path('messages', ContactView.as_view(), name='contact'),

    # blog
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_details'),
    path('blog/add/', CreateBlog.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', UpdateBlog.as_view(), name='blog_update'),
    path('blog/delete', DeleteBlog.as_view(), name='blog_delete'),

    # event
    path('event/', EventListView.as_view(), name='event_list'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('event/add/', CreateEvent.as_view(), name='event_create'),
    path('event/<int:pk>/update/', UpdateEvent.as_view(), name='event_update'),
    path('event/delete', DeleteEvent.as_view(), name='event_delete'),

]

knn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userapp.urls')),
    path('', include('base.urls')),
    path('', include('books.urls')),
    path('', include('blogs.urls')),
    path('', include('discussion.urls')),
    path('', include('events.urls')),

    path('dashboard/', include('dashboard.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/models.py
from django.db import models


class BaseInfo(models.Model):
    comapny_name = models.CharField(max_length=50, null=True, blank=True)
    contact = models.CharField(max_length=50, null=True, blank=True)
    address1 = models.CharField(max_length=256, null=True, blank=True)
    street = models.CharField(max_length=256, null=True, blank=True)
    country = models.CharField(max_length=256, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    logo = models.ImageField(upload_to='company/', null=True, blank=True)


class Ads(models.Model):
    AD_TYPE = (
        ('Hero','Hero'),
        ('HeroFooter','HeroFooter'),
        ('Home Left','Home Left'),
        ('Home Right','Home Right'),
    )
    image = models.ImageField(upload_to='ads/', null=True, blank=True)
    ad_type = models.CharField(choices=AD_TYPE, max_length=256)
    title = models.CharField(max_length=256)
    sub_title = models.CharField(max_length=256, null=True, blank=True)
    action_url = models.URLField(null=True, blank=True)
    status = models.BooleanField(default=True)


class Contact(models.Model):
    contacted_by = models.CharField(max_length=256, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone_number = models.CharField(max_length=256, blank=True, null=True)
    message = models.TextField(max_length=500)

    
    

base/forms.py
from django.forms import ModelForm

from .models import Contact, Ads


class BaseForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.field[field].widget.attrs['class'] = 'form-control'


class ContactForm(BaseForm):
    class Meta:
        model = Contact
        fields = (
            'contacted_by',
            'email',
            'phone_number',
            'message'
        )


class AdForm(BaseForm):
    class Meta:
        model = Ads
        fields = (
            'image',
            'title',
            'sub_title',
            'ad_type',
            'action_url',
            'status'
        )

        

base/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from .models import Contact
from .forms import ContactForm

from books.views import BaseMixin


class ContactView(BaseMixin, CreateView):
    model = Contact
    form_class = ContactForm
    queryset = Contact.objects.none()
    template_name = 'base/contact.html'
    success_url = reverse_lazy('contact')


class TermAndConditionView(BaseMixin, TemplateView):
    template_name = 'base/term.html'


class AboutUsView(BaseMixin, TemplateView):
    template_name = 'base/aboutus.html'

    

templates/dashboard_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link href="{% static 'css/vendors.style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet"></head>

    <title>{% block title %}  {% endblock %}</title>
</head>
<body>
    
<body>
    <div class="dashboard-app">
      <aside class="sidebar">
        <a href="books.html">
          <img src="{% static 'image/dashboard/logo_white.png' %}" alt="" class="img-fluid d-block mx-auto logo" />
        </a>
  
        <ul class="menu">
          <li >
            <a href="{% url 'dashboard:home' %}"><span class="icon-books"></span> Dashboard</a>
          </li>
          <li >
            <a href="{% url 'dashboard:book_list' %}"><span class="icon-books"></span> Books</a>
          </li>
  
          <li>
            <a href="{% url 'dashboard:user_list' %}"><span class="icon-users"></span>Member</a>
          </li>
  
          <li>
            <a href="{% url 'dashboard:deposit_list' %}"><span class="icon-deposit"></span>Deposit</a>
          </li>
  
          <li>
            <a href="{% url 'dashboard:category_list' %}"><span class="icon-file-text2"></span>Category</a>
          </li>
  {% comment %}
          <li>
            <a href=""><span class="icon-file-empty"></span>Notify Users</a>
          </li>
  {% endcomment %}
          <li>
            <a href="{% url 'dashboard:request_list' %}"><span class="icon-file-empty"></span>User Request</a>
          </li>
          <li>
            <a href="{% url 'dashboard:orders' %}"><span class="icon-file-empty"></span>Orders</a>
          </li>
          <li>
            <a href="{% url 'dashboard:ads' %}"><span class="icon-file-empty"></span>Ads</a>
          </li>
          <li>
            <a href="{% url 'dashboard:blog_list' %}"><span class="icon-file-empty"></span>Blogs</a>
          </li>
          <li>
            <a href="{% url 'dashboard:event_list' %}"><span class="icon-file-empty"></span>Event</a>
          </li>
  
        </ul>
        <div class="copyright"><span>
  
            &copy; 2021 Dashboard
          </span>
        </div>
      </aside>
      <main class="dashboard--main">
        <header class="header">
          <div class="icon-menu" id="toggler"></div>
          <div class="des text-dark ml-3">Dashboard</div>
          <div class="user--area">
  
            <div class="dropdown">
              <a class="d-flex" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false" href="">
                <div class="notification-icon mr-3">
                  <span class="icon-bell1 icon-active"></span>
                  <div class="notification-dot"></div>
                </div>
              </a>
              <div class="dropdown-menu dropdown-menu-right dropdown-notify" aria-labelledby="dropdownMenuLink">
                <div class="top">
                  <p>Notifications Section</p>
  
                </div>
                <ul class="line line-notify scrollable">
                 
                  {% for notice in notificaitons %}
                  <li>
                    <div class="d-flex align-items-center">
  
                      <div class="notify-icon info-1" href="#/">
                        <i class="icon-books"></i>
                      </div>
                      <div class="ml-3">
                        <p>{{notice.message}}</p>
                        <small>{{notice.date}}</small>
                      </div>
                    </div>
  
                  </li>
                  {% endfor %}
                 
                </ul>
              </div>
            </div>
  
            <a href="#" class="">
              
              <img src="  {% static 'image/dashboard/user-male.png' %}" alt="user-image" class="profile" />
            </a>
  
            <div class="dropdown mr-3">
              <a href="#" class="d-flex align-items-center" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <div class="small text-dark font-regular user--name">{{request.user.first_name}} {{request.user.last_name}}
                  <div class="badge badge-success">Admin</div>
                </div>
                <span class="icon-triangle-down"></span>
              </a>
  
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <p class="px-3">{{request.user.email}}</p>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
              </div>
            </div>
  
          </div>
        </header>
        {% block content %}

        {% endblock %}

      </main>
    </div>
  <script type="text/javascript" src="{% static 'js/vendors.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/home.js' %}"></script></body>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

</body>
</html>

templates/get_req_pagination.html
<div class="">
    <div class="pagination d-flex justify-content-center mt-2">

        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?search={{request.GET.search}}&page=1" class="btn btn-outline-primary">&laquo; First</a>
                <a href="?search={{request.GET.search}}&page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary">Previous</a>
            {% endif %}
    
           
    
            {% if page_obj.has_next %}
                <a href="?search={{request.GET.search}}&page={{ page_obj.next_page_number }}" class="btn btn-outline-primary">Next</a>
                <a href="?search={{request.GET.search}}&page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-primary">Last &raquo;</a>
            {% endif %}
        </span>
</div>

    
</div>

templates/pagination.html
<div class="">
    <div class="pagination d-flex justify-content-center mt-2">

        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1" class="btn btn-outline-primary">&laquo; First</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary">Previous</a>
            {% endif %}
    
           
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary">Next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-primary">Last &raquo;</a>
            {% endif %}
        </span>
</div>

    
</div>

templates/settings.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}  {% endblock %}</title>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/plugins.css' %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/main.css' %}" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'image/favicon.ico' %}">
</head>
<body>
    <div class="container">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>