dashboard/urls.py
from django.urls import path

from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardView.as_view(), name='home'),
    # user 
    path('user/', UserListView.as_view(), name='user_list'),
    path('user/approved/', ApprovedUserList.as_view(), name='approved_users'),
    path('user/unapproved/', UnapprovedUserList.as_view(), name='unapproved_users'),
    path('user/<str:username>/', UserDetail.as_view(), name='user_detail'),

    path('user/<str:username>/accept/', ApproveUser.as_view(), name='approve'),
    path('user/<str:username>/reject/', RejectUser.as_view(), name='reject'),
    path('user/<str:username>/book/receive/', ReceiveBook.as_view(), name='receive_book'),

    # books
    path('book/add/', AddBook.as_view(), name='add_book'),
    path('book/', BookList.as_view(), name='book_list'),
    path('book/available/', AvailabelBookList.as_view(), name='available_books'),
    path('book/unavailable/', UnavailabelBookList.as_view(), name='unavailable_books'),

    path('book/<str:slug>/', BookDetail.as_view(), name='book_details'),
    path('book/<str:slug>/update/', UpdateBook.as_view(), name='book_update'),
    path('book/delete', DeleteBook.as_view(), name='book_delete'),

    # deposit
    path('deposit/', DepositList.as_view(), name='deposit_list'),
    path('deposit/<int:pk>/', DepositDetail.as_view(), name='deposit_detail'),
    path('deposit/<int:pk>/verify/', VerifyDeposit.as_view(), name='verify'),
    path('deposit/<int:pk>/unverify/', RejectDeposit.as_view(), name='unverify'),

    # category
    path('category/add/', AddCategory.as_view(), name='add_category'),
    path('category/', CategoryList.as_view(), name='category_list'),
    path('category/<slug:slug>/', CategoryDetail.as_view(), name='category_detail'),
    path('category/<slug:slug>/update/', CategoryUpdate.as_view(), name='category_update'),
    path('category/delete', CategoryDelete.as_view(), name='category_delete'),

    # RequestList
    path('request/', RequestList.as_view(), name='request_list'),

    # orders
    path('orders/', OrderList.as_view(), name='orders'),
    path('orders/delivered/', CompletedOrderList.as_view(), name='delivered_orders'),
    path('orders/canceled/', CanceledOrderList.as_view(), name='canceled_orders'),
    path('orders/dispatched/', DispatchedOrderList.as_view(), name='dispatched_orders'),

    path('orders/<int:pk>/dispatch/', DispatchOrder.as_view(), name='dispatched'),
    path('orders/<int:pk>/cancel/', CanceleOrder.as_view(), name='canceled'),
    path('orders/<int:pk>/delivered/', DelivereOrder.as_view(), name='delivered'),

    # search
    path('user/search', UserSearch.as_view(), name='user_search'),
    path('book/search', BookSearch.as_view(), name='book_search'),
    path('order/search', OrderSearch.as_view(), name='order_search'),

    # ads
    path('ads/', AdsView.as_view(), name='ads'),
    path('ads/<int:pk>/', AdsDetailView.as_view(), name='ad_details'),
    path('ads/add/', CreateAd.as_view(), name='ad_create'),
    path('ads/<int:pk>/update/', UpdateAd.as_view(), name='ad_update'),
    path('ads/<int:pk>/delete', DeleteAd.as_view(), name='ad_delete'),

    # contact
    path('messages', ContactView.as_view(), name='contact'),

    # blog
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_details'),
    path('blog/add/', CreateBlog.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', UpdateBlog.as_view(), name='blog_update'),
    path('blog/delete', DeleteBlog.as_view(), name='blog_delete'),

    # event
    path('event/', EventListView.as_view(), name='event_list'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('event/add/', CreateEvent.as_view(), name='event_create'),
    path('event/<int:pk>/update/', UpdateEvent.as_view(), name='event_update'),
    path('event/delete', DeleteEvent.as_view(), name='event_delete'),

]

knn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userapp.urls')),
    path('', include('base.urls')),
    path('', include('books.urls')),
    path('', include('blogs.urls')),
    path('', include('discussion.urls')),
    path('', include('events.urls')),

    path('dashboard/', include('dashboard.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.base import TemplateView
from django.views.generic.edit import DeleteView
 
from .permissions import IsAdminMixin
from django.http import JsonResponse


from django.contrib.auth import get_user_model
from django.db.models import Q,F
from books.models import Book, Category, BookUpload, Order
from userapp.models import Request, Deposit, Notification as Notice
from books.forms import BookForm, CategoryForm, AdminBookForm
from base.models import Ads, Contact
from base.forms import AdForm
from blogs.models import Blog
from discussion.models import Quesiton
from events.models import Event
from blogs.forms import Blogform
from events.forms import Eventform

User = get_user_model()

class BaseMixin(IsAdminMixin):
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['notificaitons'] = Notice.objects.all().order_by('-id')
        return context_data


class DashboardView(BaseMixin, TemplateView):
    template_name = 'dashboard/home.html'

    def get_context_data(self, **kwargs):
        context_data =  super().get_context_data(**kwargs)
        context_data['total_users'] = User.objects.all().count()
        context_data['total_books'] = Book.objects.all().count()
        context_data['new_request'] = Request.objects.filter(status=False).count()
        context_data['new_order'] = Order.objects.filter(delivery_status='none').count()

        return context_data


class UserMixin(BaseMixin, ListView):
    model = User
    template_name = 'dashboard/userlist.html'
    paginate_by = 30


class UserListView(UserMixin):
    queryset = User.objects.all().order_by('-id')


class ApprovedUserList(UserMixin):
    queryset = User.objects.filter(approved=True).order_by('-id')


class UnapprovedUserList(UserMixin):
    queryset = User.objects.filter(approved=False).order_by('-id')


class UserSearch(UserMixin):
    def get_queryset(self):
        data = str(self.request.GET.get("q"))
        return User.objects.filter(Q(username__icontains=data) | Q(contact__icontains=data) | Q(email__icontains=data)).order_by('-id')        


class UserDetail(BaseMixin, DetailView):
    model = User
    template_name = 'dashboard/user_detail.html'
    queryset = User.objects.all()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        user = self.get_object()
        context_data['books'] = BookUpload.objects.select_related('book').filter(added_by=user)
        context_data['deposits'] = Deposit.objects.filter(user=user)
        return context_data

    def get_object(self, **kwargs):
        return get_object_or_404(User, username=self.kwargs.get('username'))


class ApproveUser(BaseMixin, View):
    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        req =  Request.objects.filter(user=user, status=False).order_by('-id')
        if req.exists():    
            req.update(status=True)
        user.approved = True
        user.save()
        return redirect(request.META.get('HTTP_REFERER'))


class ReceiveBook(BaseMixin, View):
    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        uploads = BookUpload.objects.filter(added_by=user)
        uploads.update(status='approved')
        books_id = uploads.values_list('book_id', flat=True)
        books = Book.objects.filter(id__in=books_id)
        books.update(available=F('available')+1)
        user.books_received = True
        user.save()
        return redirect(request.META.get('HTTP_REFERER'))


class RejectUser(BaseMixin, View):
    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        user.approved = False
        user.save()
        return redirect(request.META.get('HTTP_REFERER'))


class AddEvents(BaseMixin):
    pass


class BookMixin(BaseMixin, ListView):
    model = Book
    template_name = 'dashboard/booklist.html'
    paginate_by = 30


class BookList(BookMixin):
    queryset = Book.objects.filter(status=True).order_by('-id')


class AvailabelBookList(BookMixin):
    queryset = Book.objects.filter(available__gt=0, status=True).order_by('-id')


class UnavailabelBookList(BookMixin):
    queryset = Book.objects.filter(available__lte=0, status=True).order_by('-id')


class BookSearch(BookMixin):
    def get_queryset(self):
        return Book.objects.filter(Q(book_name__icontains=self.request.GET.get("q")) | Q(isbn__icontains=self.request.GET.get("q"))).order_by('-id')


class AddBook(BaseMixin, CreateView):
    model = Book
    template_name = 'dashboard/category_create.html'
    queryset = Book.objects.none()
    form_class = BookForm

    def post(self, request, *args, **kwargs):
        form = BookForm(request.POST, request.FILES)        
        if form.is_valid():
            isbn = form.cleaned_data.get('isbn_number')
            print(isbn)
            if Book.objects.filter(isbn=isbn).exists():
                book = get_object_or_404(Book, isbn=isbn)
            else:
                book = form.save(commit=False)
                book.isbn = isbn
                book.save()
            BookUpload.objects.create(book=book, added_by=request.user, status='approved')
            book.save()
            return redirect(reverse_lazy('dashboard:book_list'))
        else:
            print(form.errors)
        return redirect(request.META.get('HTTP_REFERER'))


class BookDetail(BaseMixin, DetailView):
    model = Book
    template_name = 'dashboard/book_details.html'
    queryset = Book.objects.all()

    def get_context_data(self, **kwargs):
        context_data =  super().get_context_data(**kwargs)
        context_data['book_owners'] = BookUpload.objects.select_related('added_by').filter(book=self.get_object())
        return context_data


class UpdateBook(BaseMixin, UpdateView):
    model = Book
    template_name = 'dashboard/category_update.html'
    queryset = Book.objects.all()
    form_class = AdminBookForm

    def get_success_url(self):
        print('success')
        return reverse('dashboard:book_details',kwargs={'slug':self.get_object().slug})


class DeleteBook(BaseMixin, View):
    def get(self, request):
        id = request.GET.get("pk", None)
        Book.objects.get(id=id).delete()
        data = {"deleted": True}
        return JsonResponse(data)


class RequestList(BaseMixin, ListView):
    model = Request
    template_name = 'dashboard/request_list.html'
    paginate_by = 30
    queryset = Request.objects.select_related('user').filter(status=False).order_by('-id')


class Notification(BaseMixin):
    pass


class UserNotificationList(BaseMixin):
    pass


class CreateNotification(BaseMixin):
    pass


class AddCategory(BaseMixin, CreateView):
    model = Category
    template_name = 'dashboard/category_create.html'
    queryset = Category.objects.none()
    form_class = CategoryForm
    success_url = reverse_lazy('dashboard:category_list')


class CategoryList(BaseMixin, ListView):
    model = Category
    template_name = 'dashboard/category_list.html'
    paginate_by = 30
    queryset = Category.objects.all().order_by('-id')


class CategoryDetail(BaseMixin, DetailView):
    model = Category
    template_name = 'dashboard/category_details.html'
    queryset = Category.objects.all()


class CategoryUpdate(BaseMixin, UpdateView):
    model = Category
    template_name = 'dashboard/category_update.html'
    queryset = Category.objects.all()
    form_class = CategoryForm

    def get_success_url(self):
        return reverse('dashboard:category_detail',kwargs={'slug':self.get_object().slug})


class CategoryDelete(BaseMixin, View):
    def get(self, request):
        id = request.GET.get("pk", None)
        Category.objects.get(id=id).delete()
        data = {"deleted": True}
        return JsonResponse(data)


class DepositList(BaseMixin, ListView):
    model = Deposit
    template_name = 'dashboard/deposit_list.html'
    paginate_by = 30
    queryset = Deposit.objects.select_related('user').all().order_by('-id')


class DepositDetail(BaseMixin, DetailView):
    model = Deposit
    template_name = 'dashboard/deposit_detail.html'
    queryset = Deposit.objects.all()


class VerifyDeposit(View):
    def get(self, request, *args, **kwargs):
        deposit = get_object_or_404(Deposit, pk=self.kwargs.get('pk'))
        deposit.verified = True
        deposit.save()
        return redirect(request.META.get("HTTP_REFERER"))


class RejectDeposit(View):
    def get(self, request, *args, **kwargs):
        deposit = get_object_or_404(Deposit, pk=self.kwargs.get('pk'))
        deposit.verified = False
        deposit.save()
        return redirect(request.META.get("HTTP_REFERER"))


class OrderMixin(BaseMixin, ListView):
    model = Order
    template_name = 'dashboard/order_list.html'
    paginate_by = 30


class OrderList(OrderMixin):
    queryset = Order.objects.select_related('user').select_related('address').prefetch_related('books').filter(Q(delivery_status='none') | Q(dispatched=True, delivery_status='none' )).order_by('-id')


class CompletedOrderList(OrderMixin):
    queryset = Order.objects.select_related('user').select_related('address').prefetch_related('books').filter(delivery_status='delivered').order_by('-id')


class DispatchedOrderList(OrderMixin):
    queryset = Order.objects.select_related('user').select_related('address').prefetch_related('books').filter(dispatched=True, delivery_status='none').order_by('-id')


class CanceledOrderList(OrderMixin):
    queryset = Order.objects.select_related('user').select_related('address').prefetch_related('books').filter(delivery_status='canceled').order_by('-id')

templates/dashboard/ad_detail.html
{% extends 'dashboard_base.html' %}
{% load static %}


{% block title %}  Knowledge Network Nepal {% endblock %}

{% block content %} 


<div class="inner">
    <div class="card">
      <div class="dashboard-header mb-3">
        <h6 class="text-primary font-weight-bold">Ad details
        </h6>
       
      </div>
      <div class="row mt-4">
        <div class="col-lg-3">
            <div class="image-lg">
                {% if object.image %}
              <img src="{{object.image.url}}" alt="Ad Image">
              {% endif %}
            </div>
          </div>
        <div class="col-lg-9">
          <div class="row">
            <div class="col-lg-4">
              <div class="details">
                <h6>Name</h6>
                <p>{{object.title}} </p>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="details">
                <h6>Sub Title</h6>
                <p>{{object.sub_title}}</p>
              </div>
            </div>
            <div class="col-lg-4">
                <div class="details">
                  <h6>Type</h6>
                  <p>{{object.ad_type}}</p>
                </div>
              </div>
            <div class="col-lg-4">
              <div class="details">
                <h6>Status</h6>
                <p>{{object.status}}</p>
              </div>
            </div>
            <div class="col-lg-4">
                <div class="details">
                  <h6>URL</h6>
                  <p>{{object.action_url}}</p>
                </div>
              </div>
            <div class="col-lg-4">
                <div class="details">
                  <h6>Action</h6>
                  <a href="{% url 'dashboard:ad_update' object.pk %}" class="btn btn-primary">
                    Update
                  </a>                </div>
              </div>
      
              <div class="col-lg-4">
                <div class="details">
                  <h6>Action</h6>
                 <a class="btn btn-danger" onclick=deleteReport({{object.pk}})>Delete</a>
                                </div>
              </div>
          </div>
        </div>

      </div>
    </div>
  </div>

  <script>
    function deleteReport(pk) {
    var action = confirm("Are you sure you want to delete this ad ?");
    if (action != false) {
      $.ajax({
          url: '{% url "dashboard:ad_delete" %}',
          data: {
              'pk': pk,
          },
          dataType: 'json',
          success: function (data) {
              if (data.deleted) {
                location.href="{% url 'dashboard:ads' %}"

              }
          }
      });
    }
  }
  </script>

{% endblock %}

templates/dashboard/blog_list.html
{% extends 'dashboard_base.html' %}
{% load static %}


{% block title %}  Knowledge Network Nepal {% endblock %}

{% block content %} 

<div class="inner">

    <div class="card">
      <div class="dashboard-header mb-3">
        <h6 class="text-primary font-weight-bold">Ads
        </h6>
        <div class="d-flex align-items-center justify-content-center mt-2 mt-sm-0">
        
          <button class="btn btn-primary btn-icon ml-2">
            <a href="{% url 'dashboard:blog_create' %}">
              <i class="icon-add"></i>
              Add
            </a>
           </button>
        </div>

      </div>
      <div class="table-responsive">
        <table class="table table__small d-table">
          <thead>
            <tr>
              <th>S.N</th>
              <th>Blog</th>
              <th>Author</th>

            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td>
                <a href="{% url 'dashboard:blog_details' object.pk %}">{{object.title}}</a></td>
              <td>{{object.author}}</td>


            </tr>
            {% endfor %}

       
          </tbody>
        </table>
      </div>
    </div>
    {% include 'pagination.html' %}

  </div>




{% endblock %}

templates/dashboard/booklist.html
{% extends 'dashboard_base.html' %}
{% load static %}


{% block title %}  Knowledge Network Nepal {% endblock %}

{% block content %} 

<div class="inner">

    <div class="card">
      <div class="dashboard-header mb-3">
        <h6 class="text-primary font-weight-bold">Books
        </h6>
        <div class="d-flex align-items-center justify-content-center mt-2 mt-sm-0">
          <a href="{% url 'dashboard:book_list' %}" class="btn btn-info mx-2">All books</a>
          <a href="{% url 'dashboard:available_books' %}" class="btn btn-info mx-2">Avaialbe books</a>
          <a href="{% url 'dashboard:unavailable_books' %}" class="btn btn-info mx-2">Unavailabe books</a>

          <div class="form-group icon mb-0">
            <form class="form-inline" method="GET" action="{% url 'dashboard:book_search' %}">
              <input type="text" class="form-control" placeholder="Search" name="q">
                <button class="btn btn-outlined"><i class="icon-search"></i></button>
            </form>


          </div>
          <button class="btn btn-primary btn-icon ml-2">
            <a href="{% url 'dashboard:add_book' %}">
              <i class="icon-add"></i>
              Add
            </a>
           </button>
        </div>

      </div>
      <div class="table-responsive">
        <table class="table table__small d-table">
          <thead>
            <tr>
              <th>S.N</th>
              <th>Book Name</th>
              <th>Category</th>
              <th>Featured</th>

              <th>Status</th>

            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td>
                <a href="{% url 'dashboard:book_details' object.slug %}">{{object.book_name}}</a></td>
              <td>{{object.category}}</td>
              <td>
                {% if object.featured %}
                Featured
                {% else %}
                Not Featured
                {% endif %}
              </td>
              {% if object.available > 0 %}
              <td><span class="badge badge-success">Available</span></td>

              {% else %}
              <td><span class="badge badge-danger">Unavailable</span></td>

              {% endif %}

            </tr>
            {% endfor %}

       
          </tbody>
        </table>
      </div>
    </div>
    {% include 'pagination.html' %}

  </div>




{% endblock %}

templates/dashboard/deposit_detail.html
{{object}}
{{object.amount}}

templates/dashboard/order_list.html
{% extends 'dashboard_base.html' %}
{% load static %}


{% block title %}  Knowledge Network Nepal {% endblock %}

{% block content %} 


<div class="inner">
    <div class="card">
      <div class="dashboard-header mb-3">
        <h6 class="text-primary font-weight-bold">Orders
        </h6>
        <div class="d-flex align-items-center justify-content-center mt-2 mt-sm-0">
            <a href="{% url 'dashboard:orders' %}" class="btn btn-info mr-2">All Orders</a>
            <a href="{% url 'dashboard:dispatched_orders' %}" class="btn btn-info mr-2">Dispathced</a>
            <a href="{% url 'dashboard:delivered_orders' %}" class="btn btn-info mr-2">Delivered</a>
            <a href="{% url 'dashboard:canceled_orders' %}" class="btn btn-info mr-2">Canceled</a>

          <div class="form-group icon mb-0">

            <form class="form-inline" method="GET" action="{% url 'dashboard:order_search' %}">
              <input type="text" class="form-control" placeholder="Search" name="q">
                <button class="btn btn-outlined"><i class="icon-search"></i></button>
            </form>


          </div>

        </div>

      </div>
      <div class="table-responsive">

        <table class="table table__small d-table">
          <thead>
            <tr>
              <th>S.N</th>
              <th>Member </th>
              <th>Contact</th>
              <th>Status</th>
              <th>Books</th>
              <th>Address</th>
              <th>Action</th>

            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
        
            <tr>
              <td>{{forloop.counter}}</td>
              <td>
                  <a href="{% url 'dashboard:user_detail' object.user.username %}">
                    {{object.user.first_name}} {{object.user.last_name}} ({{object.user.username}})

                  </a>

              </td>
              <td>{{object.address.phone_number}}</td>
              <td>

                    {% if object.status == 'delivered' %}
                    Delivered
                {% elif object.status == 'canceled' %}
                    Canceled
                {% else %}
                    {% if object.dispatched %}
                    Dispatched
                    {% else %}
                    No Action
                    {% endif %}
                {% endif %}

            </td>
            <td>
                {% for book in object.books.all %}
                <a href="{% url 'dashboard:book_details' book.slug %}">
                    {{book.book_name}} (Available {{book.available}})
                </a><br>
                {% endfor %}
              </td>
          
              <td>
                {{object.address.street}} <br>  
                {{object.address.city}}
             </td>
             <td>
                 {% if object.delivery_status == 'delivered' %}
                    Delivered
                 {% elif object.delivery_status == 'canceled' %}
                    Canceled
                 {% else %}
                    {% if object.dispatched %}
                    <a href="{% url 'dashboard:delivered'  object.pk %}" class="btn btn-success">Deliver</a>
                    {% else %}
                    <a href="{% url 'dashboard:dispatched'  object.pk %}" class="btn btn-primary">Dispatch</a>
                    {% endif %}
                    <a href="{% url 'dashboard:canceled'  object.pk %}" class="btn btn-danger">Cancel</a>
                {% endif %}

             </td>

            </tr>
            {% endfor %}

       
          </tbody>
        </table>
      </div>
    </div>
    {% include 'pagination.html' %}

  </div>

{% endblock %}

templates/dashboard/user_detail.html
{% extends 'dashboard_base.html' %}
{% load static %}


{% block title %}  Knowledge Network Nepal {% endblock %}

{% block content %} 


<div class="inner">
    <div class="card">
      <div class="dashboard-header mb-3">
        <h6 class="text-primary font-weight-bold">Member details
        </h6>
        <div class="d-flex align-items-center justify-content-center mt-2 mt-sm-0">
         
        </div>
      </div>
      <div class="row mt-4">
        <div class="col-lg-3">
          <div class="image-lg">
            <img src="{% static 'image/dashboard/user-male.png' %}" alt="User">
          </div>
        </div>
        <div class="col-lg-9">
          <div class="row">
            <div class="col-lg-4">
              <div class="details">
                <h6>Name</h6>
                <p>{{object.first_name}}  {{object.last_name}} ({{object.username}})</p>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="details">
                <h6>Email</h6>
                <p>{{object.email}}</p>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="details">
                <h6>Phone Number</h6>
                <p>{{object.contact}}</p>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="details">
                <h6>Status</h6>
                <p>{% if object.approved %} Approved {% else %} Not Approved {%endif%}</p>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="details">
                <h6>Action</h6>
                {% if object.approved %}
                <a href="{% url 'dashboard:reject' object.username %}" class="btn btn-danger">Reject</a>

                 {% else %} 
                 <a href="{% url 'dashboard:approve' object.username %}" class="btn btn-success">Accept</a>

                 {%endif%}
              </div>
            </div>
            <div class="col-lg-4">
              <div class="details">
                <h6>Books</h6>
                {% if not object.books_received %}
              <a href="{% url 'dashboard:receive_book' object.username %}"class="btn btn-success">Receive book</a>
              {% else %}
                Book Already received
              {% endif %}
            </div>
            </div>
          </div>
        </div>
        <div class="table-responsive mt-4">

          <table class="table table__small d-table">
            <thead>
              <tr>
                <th>S.N</th>
                <th>Book Name </th>
                <th>Author</th>

              </tr>
            </thead>
            <tbody>
            {% for book in books %}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{book.book.book_name}}</td>
                <td>{{book.book.author}}</td>
              </tr>
              {% endfor %}

            </tbody>
          </table>
          <div class="table-responsive mt-4">

          <table class="table table__small d-table">
            <thead>
              <tr>
                <th>S.N</th>
                <th>Deposit Amount</th>
                <th>Voucher</th>
                <th>Verified</th>
                <th>Action</th>

              </tr>
            </thead>
            <tbody>
            {% for deposit in deposits %}
              <tr>
                <td>{{forloop.counter}}</td>
             
                <td>{{deposit.amount}}</td>
                <td>
                    <a href="{{deposit.image.url}}" target="_blank">View </a>

                </td>
                <th>
                    {% if deposit.verified %}
                        Verified
                    {% else %}
                        Unverified
                    {% endif %}
                </th>
                <td>
                  {% if deposit.verified %}
                  <a href="{% url 'dashboard:unverify' deposit.pk %}" class="btn btn-danger">Unverify</a>
                  {% else %}
                  <a href="{% url 'dashboard:verify' deposit.pk %}" class="btn btn-success">Vefiry</a>
                  {% endif %}
                </td>

              </tr>
              {% endfor %}

            </tbody>
          </table>
          </div>
        </div>
      </div>
    </div>
  </div>



{% endblock %}

templates/dashboard/userlist.html
{% extends 'dashboard_base.html' %}
{% load static %}


{% block title %}  Knowledge Network Nepal {% endblock %}

{% block content %} 


<div class="inner">
    <div class="card">
      <div class="dashboard-header mb-3">
        <h6 class="text-primary font-weight-bold">Members
        </h6>
        <div class="d-flex align-items-center justify-content-center mt-2 mt-sm-0">
          <a href="{% url 'dashboard:user_list' %}" class="btn btn-info mx-2">All Users</a>
          <a href="{% url 'dashboard:approved_users' %}" class="btn btn-info mx-2">Approved users</a>
          <a href="{% url 'dashboard:unapproved_users' %}" class="btn btn-info mx-2">Unapproved users</a>
          <div class="form-group icon mb-0">
            <form class="form-inline" method="GET" action="{% url 'dashboard:user_search' %}">
              <input type="text" class="form-control" placeholder="Search" name="q">
                <button class="btn"><i class="icon-search"></i></button>
            </form>



          </div>

        </div>

      </div>
      <div class="table-responsive">

        <table class="table table__small d-table">
          <thead>
            <tr>
              <th>S.N</th>
              <th>Name </th>
              <th>Email</th>
              <th>Status</th>
              
              <th>Phone</th>


            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
        
            <tr>
              <td>{{forloop.counter}}</td>
              <td>
                <a href="{% url 'dashboard:user_detail' object.username %}" class="d-flex align-item-center">
                  <div class="image mr-2">
                    <img src="{% static  'image/dashboard/user-male.png' %}" alt="user">
                  </div>
                  <p>{{object.first_name}} {{object.last_name}}  ({{object.username}})</p>
                </a>
              </td>
              <td>{{object.email}}</td>
              <td>{{object.approved}}</td>

              <td>{{object.contact}}</td>

            </tr>
            {% endfor %}

       
          </tbody>
        </table>
      </div>
    </div>
    {% include 'pagination.html' %}

  </div>



{% endblock %}